const housingPrices = [
    {
        "order_type_id": 1,
        "background_color": "f0f0f0",
        "coordinates": {
            "latitude": "32.0855535365854",
            "longitude": "34.8065558292683"
        },
        "row_1": "בנימין",
        "title_1": "בנימין",
        "title_2": "דירה",
        "row_2": "דירה, תל בנימין, רמת גן",
        "row_3": [
            "3.5 חדרים",
            "130 מ\"ר",
            "6"
        ],
        "row_4": [
            {
                "key": "rooms",
                "label": "חדרים",
                "value": 3.5
            },
            {
                "key": "floor",
                "label": "קומה",
                "value": 6
            },
            {
                "key": "SquareMeter",
                "label": "מ\"ר",
                "value": "130 "
            }
        ],
        "line_1": "3.5 חדרים",
        "line_2": "6",
        "external": [],
        "promotional_ad": 0,
        "ad_type": "ad",
        "type": "ad",
        "can_hide": 0,
        "is_hidden": 0,
        "img_url": null,
        "images": [],
        "images_urls": [
            "https://img.yad2.co.il/Pic/202202/07/2_5/o/y2_1_2rSORlXoIL_20220207.jpg",
            "https://img.yad2.co.il/Pic/202202/07/2_5/o/y2_2_mA903ZdM2R_20220207.jpg",
            "https://img.yad2.co.il/Pic/202202/07/2_5/o/y2_3_s7RJzPS3pG_20220207.jpg",
            "https://img.yad2.co.il/Pic/202202/07/2_5/o/y2_4_gclNvG5kFR_20220207.jpg",
            "https://img.yad2.co.il/Pic/202202/07/2_5/o/y2_5_456BKszC0Y_20220207.jpg",
            "https://img.yad2.co.il/Pic/202202/07/2_5/o/y2_6_Vr5YWvGdtT_20220207.jpg"
        ],
        "images_count": 0,
        "merchant": true,
        "link_token": "1h204wqo",
        "ad_highlight_type": "none",
        "highlight_text": "בלעדי",
        "is_liked": 0,
        "like_count": 0,
        "line_1_text_color": "",
        "line_2_text_color": "808080",
        "can_change_layout": 1,
        "default_layout": "system",
        "remove_on_unlike": false,
        "video_url": null,
        "mp4_video_url": null,
        "updated_at": "עודכן היום",
        "price": "2,790,000 ₪",
        "currency": "₪",
        "uid": "fuobHM+Ju3qejFDyOI2gySvd9H9TV8uUesarp3FIhXs=",
        "search_text": "דירה תיווך מכירה חדרים ב רמת גן , תל בנימין , בנימין $HomeNum קומה $Floor_text מתוך $TotalFloor_text קומות. $FurnitureInfo בטיפולנו הבלעדי בשכונת תל בנימין המבוקשת ברמת גן דירה ענקית שמורה ומטופחת.\n\nכ- 130 מ\"ר בנוי\nכיום 3.5 חדרים (ניתן להגדיל)\nריצוף שיש איטלקי\n2 דיירים בקומה\nנוף פתוח\nשטחי אירוח מרווחים\nסוויטת הורים ענקית\nמיקום מנצח קרוב להכל\nמיזוג אויר (מזגנים מפוצלים)\nחניה בטאבו שני ברטל דירה 3 $Floor_text $TotalFloor_text $Amudim_text $Furniture_text $PandorDoors_text מיזוג מעלית חניה סורגים גישה לנכים אזור רמת גן וגבעתיים מיידי $mamad_text $patio_text $storeroom_text $sunpatio_text ₪ משופצת $Porch_text $yehidatdiur_text במצב שמור הצג רחוב $show_home_text מזגן תדיראן עם מחיר, חניה, הצג רק מושבים וקיבוצים, מעלית, מיזוג, מיזוג, סורגים, גישה לנכים, מיידי, משופצת, בבלעדיות, מזגן תדיראן, הצג רחוב 3 חדרים | 130 מ״ר | 6 בנימין , תל בנימין",
        "ad_number": 55748099,
        "customer_id": 7303088,
        "cat_id": "2",
        "subcat_id": "5",
        "record_id": 2610946,
        "date_added": "2022-02-07 12:53:31",
        "area_id": 3,
        "city": "רמת גן",
        "neighborhood": "תל בנימין",
        "street": "בנימין",
        "address_home_number": null,
        "date_of_entry": "2022-02-07 00:00:00",
        "contact_name": "שני ברטל",
        "date": "2022-04-23 16:15:25",
        "city_code": "8600",
        "id": "1h204wqo",
        "topAreaID_text": "מרכז",
        "AreaID_text": "אזור רמת גן וגבעתיים",
        "HomeTypeID_text": "דירה",
        "Parking_text": "חניה",
        "Elevator_text": "מעלית",
        "AirConditioner_text": "מיזוג",
        "Grating_text": "סורגים",
        "mamad_text": "",
        "patio_text": "",
        "storeroom_text": "",
        "handicapped_text": "גישה לנכים",
        "Immediate_text": "מיידי",
        "PandorDoors_text": "",
        "Furniture_text": "",
        "Meshupatz_text": "משופצת",
        "sunpatio_text": "",
        "AssetClassificationID_text": "במצב שמור",
        "Rooms_text": 3,
        "Amudim_text": "",
        "yehidatdiur_text": "",
        "Tadiran_text": "מזגן תדיראן",
        "show_street_text": "הצג רחוב",
        "show_home_text": "",
        "Porch_text": "",
        "currency_text": "₪",
        "square_meters": 130,
        "address_more": "בשכונת תל בנימין המבוקשת 130 מ\"ר אפשר להפוך ל 4.5",
        "line_3": "אוורסט נדל\"ן - לירן קוממי",
        "merchant_name": "אוורסט נדל\"ן - לירן קוממי",
        "office_logo_url": "//img.yad2.co.il/Pic/TivMiniSite/logo100_2_7_732030_20190107090128-l.jpg?t=1650719741475",
        "office_about": "אוורסט נדל\"ן- בניהול לירן קוממי, מומחים בשיווק ותיווך נדל\"ן בבקעת אונו.אצלנו תמצאו את הבתים הנחשקים ביותר באזור,\nתקבלו שרות מהמתווכים הוותיקים שלנו , עתירי הניסיון,\nותיהנו משירות שיווקי חסר תקדים לנכס-- נסו אותנו!\nאנחנו הכתובת שלכם!\nמרכז הבמה || הכרמל 20 || קומה 1 || 03-6037777\nאוורסט, פסגת השרות בנדל״ן.\nאנו שמחים לבשר לכם על פתיחתו של משרדנו החדש לשיווק ותיווך דירות ומגרשים בארץ ובחו״ל. ?אוורסט? חרטה על דגלה להיות סמן ימני בתחום השרות והמקצועיות ללקוח. בשילוב של אמינות וניסיון עשיר, אנו נעשה ה",
        "IsVisibleForReco": false,
        "hood_id": 236,
        "Rooms": 3.5,
        "HomeTypeID": 1
    },
    {
        "order_type_id": 1,
        "background_color": "f0f0f0",
        "coordinates": {
            "latitude": "32.077592",
            "longitude": "34.80815"
        },
        "row_1": "בורוכוב",
        "title_1": "בורוכוב",
        "title_2": "דירה",
        "row_2": "דירה, גבעתיים",
        "row_3": [
            "4 חדרים",
            "89 מ\"ר",
            "קומת קרקע"
        ],
        "row_4": [
            {
                "key": "rooms",
                "label": "חדרים",
                "value": 4
            },
            {
                "key": "floor",
                "label": "קומה",
                "value": "קרקע"
            },
            {
                "key": "SquareMeter",
                "label": "מ\"ר",
                "value": "89 "
            }
        ],
        "line_1": "4 חדרים",
        "line_2": "קומת קרקע",
        "external": [],
        "promotional_ad": 0,
        "ad_type": "ad",
        "type": "ad",
        "can_hide": 0,
        "is_hidden": 0,
        "img_url": null,
        "images": [],
        "images_urls": [
            "https://img.yad2.co.il/Pic/202203/06/2_5/o/y2_1_999376_20220306.jpg",
            "https://img.yad2.co.il/Pic/202203/06/2_5/o/y2_12_997377_20220306.jpg",
            "https://img.yad2.co.il/Pic/202203/06/2_5/o/y2_11_999701_20220306.jpg",
            "https://img.yad2.co.il/Pic/202203/06/2_5/o/y2_10_999370_20220306.jpg",
            "https://img.yad2.co.il/Pic/202203/06/2_5/o/y2_15__993317_20220306.jpg",
            "https://img.yad2.co.il/Pic/202203/06/2_5/o/y2_14_996431_20220306.jpg",
            "https://img.yad2.co.il/Pic/202203/06/2_5/o/y2_13_998264_20220306.jpg",
            "https://img.yad2.co.il/Pic/202203/06/2_5/o/y2_3_992724_20220306.jpg",
            "https://img.yad2.co.il/Pic/202203/06/2_5/o/y2_2_995304_20220306.jpg",
            "https://img.yad2.co.il/Pic/202203/06/2_5/o/y2_15_997497_20220306.jpg",
            "https://img.yad2.co.il/Pic/202203/06/2_5/o/y2_4_995091_20220306.jpg",
            "https://img.yad2.co.il/Pic/202203/06/2_5/o/y2_5_992073_20220306.jpg",
            "https://img.yad2.co.il/Pic/202203/06/2_5/o/y2_7_993898_20220306.jpg",
            "https://img.yad2.co.il/Pic/202203/06/2_5/o/y2_8_996069_20220306.jpg"
        ],
        "images_count": 0,
        "merchant": true,
        "link_token": "2zvqq14h",
        "ad_highlight_type": "none",
        "highlight_text": "בלעדי",
        "is_liked": 0,
        "like_count": 0,
        "line_1_text_color": "",
        "line_2_text_color": "808080",
        "can_change_layout": 1,
        "default_layout": "system",
        "remove_on_unlike": false,
        "video_url": null,
        "mp4_video_url": null,
        "updated_at": "עודכן היום",
        "price": "2,890,000 ₪",
        "currency": "₪",
        "uid": "aOeAMPf8SLWRjUEMaWCJ8RQq2nFU7TdeE8JfV7bD8og=",
        "search_text": "דירה תיווך מכירה חדרים ב גבעתיים , בורוכוב , $Address $HomeNum קומה $Floor_text מתוך $TotalFloor_text קומות. $FurnitureInfo בבלעדיות. דירת 4 חד' בקומת קרקע בבניין לאחר תמ\"א 38-1. משופצת  82 מ\"ר +מ. שמש  כ 7 מ\"ר, כולל ממ\"ד. הדירה מתמזגת לגינה נעימה וירוקה שמקיפה אותה מכל עבר(לא בטאבו)ובנוסף פונה לגן הזיכרון שכ' בורוכוב! 3 כווני אוויר נוף ירוק!\nבמיקום מעולה ומרחק נגיעה מויצמן וללב העניינים, בתי הקפה, קניות וכו'. * מצויינת למי שמחפש נגישות  להכל מצד אחד ושקטה מאוד מצד שני. נגישה לנכים. *כניסה מיידית! טובה למגורים/להשקעה. אלברט פנחס דירה 4 $Floor_text $TotalFloor_text עמודים $Furniture_text $PandorDoors_text מיזוג $Elevator_text $Parking_text $Grating_text גישה לנכים אזור רמת גן וגבעתיים מיידי $mamad_text מרפסת $storeroom_text $sunpatio_text ₪ משופצת $Porch_text $yehidatdiur_text משופץ $show_street_text $show_home_text $Tadiran_text עם מחיר, הצג רק מושבים וקיבוצים, מיזוג, מיזוג, מרפסת, גישה לנכים, מיידי, משופצת, בבלעדיות, עמודים 4 חדרים | 89 מ״ר , בורוכוב",
        "ad_number": 49061734,
        "customer_id": 3637918,
        "cat_id": "2",
        "subcat_id": "5",
        "record_id": 2643887,
        "date_added": "2022-03-06 21:53:54",
        "area_id": 3,
        "city": "גבעתיים",
        "neighborhood": "בורוכוב",
        "street": null,
        "address_home_number": null,
        "date_of_entry": "2022-04-19 00:00:00",
        "contact_name": "אלברט פנחס",
        "date": "2022-04-23 16:45:49",
        "city_code": "6300",
        "id": "2zvqq14h",
        "topAreaID_text": "מרכז",
        "AreaID_text": "אזור רמת גן וגבעתיים",
        "HomeTypeID_text": "דירה",
        "Parking_text": "",
        "Elevator_text": "",
        "AirConditioner_text": "מיזוג",
        "Grating_text": "",
        "mamad_text": "",
        "patio_text": "מרפסת",
        "storeroom_text": "",
        "handicapped_text": "גישה לנכים",
        "Immediate_text": "מיידי",
        "PandorDoors_text": "",
        "Furniture_text": "",
        "Meshupatz_text": "משופצת",
        "sunpatio_text": "",
        "AssetClassificationID_text": "משופץ",
        "Rooms_text": 4,
        "Amudim_text": "עמודים",
        "yehidatdiur_text": "",
        "Tadiran_text": "",
        "show_street_text": "",
        "show_home_text": "",
        "Porch_text": "",
        "currency_text": "₪",
        "square_meters": 89,
        "line_3": "רדיוס נדל\"ן",
        "merchant_name": "רדיוס נדל\"ן",
        "office_logo_url": "//img.yad2.co.il/Pic/TivMiniSite/y2_1_07696_20200720180706.jpeg?t=1650721565428",
        "office_about": "\"רדיוס נדל\"ן\" הינו משרד לתיווך ושיווק נדל\"ן מאז שנת 2012, בניהולו ובבעלותו של אלברט פנחס.המשרד ממוקם ברח' שינקין 54 בגבעתיים ומתמחה בעיקר באזור גבעתיים ורמת גן במכירה והשכרה של נדל\"ן למגורים, דירות יד שניה ודירות חדשות וכן במכירה והשכרה של חנויות/מישרדים. משרדנו מונה צוות של 4 אנשי מקצוע ממוקדים, חדורי מוטיבציה ומיומנים, המובילים במקצועיות וביעילות את עסקאות הנדל\"ן.  ברשותינו מאגר קונים גדול ואיכותי שמתחדש כל הזמן ומיגוון רחב של כלים שיווקיים ויכולות שיווקיות מוכחות.בעלי נכסים מוזמנים לפנות אלינו לצורך קבלת ייעוץ טרם המכירה ולקביעת מחיר אופטימלי בשיווק הנכס.נשמח לעשות אתכם עסקים טובים ולהצליח ביחד !",
        "IsVisibleForReco": false,
        "hood_id": 355,
        "Rooms": 4,
        "HomeTypeID": 1
    },
    {
        "order_type_id": 1,
        "background_color": "f0f0f0",
        "coordinates": {
            "latitude": "32.074056902439",
            "longitude": "34.817200804878"
        },
        "row_1": "המעלות",
        "title_1": "המעלות",
        "title_2": "דירה",
        "row_2": "דירה, שינקין, גבעתיים",
        "row_3": [
            "4 חדרים",
            "80 מ\"ר",
            "קומת קרקע"
        ],
        "row_4": [
            {
                "key": "rooms",
                "label": "חדרים",
                "value": 4
            },
            {
                "key": "floor",
                "label": "קומה",
                "value": "קרקע"
            },
            {
                "key": "SquareMeter",
                "label": "מ\"ר",
                "value": "80 "
            }
        ],
        "line_1": "4 חדרים",
        "line_2": "קומת קרקע",
        "external": [],
        "promotional_ad": 0,
        "ad_type": "ad",
        "type": "ad",
        "can_hide": 0,
        "is_hidden": 0,
        "img_url": "https://img.yad2.co.il/Pic/202202/08/2_5/o/y2_1_06046_20220208140851.jpeg",
        "images": {
            "Image1": {
                "src": "https://img.yad2.co.il/Pic/202202/08/2_5/o/y2_1_06046_20220208140851.jpeg"
            },
            "Image2": {
                "src": "https://img.yad2.co.il/Pic/202202/08/2_5/o/y2_2_01213_20220208140909.jpeg"
            },
            "Image3": {
                "src": "https://img.yad2.co.il/Pic/202202/08/2_5/o/y2_3_08634_20220208140928.jpeg"
            },
            "Image4": {
                "src": "https://img.yad2.co.il/Pic/202202/08/2_5/o/y2_4_03326_20220208140940.jpeg"
            },
            "Image5": {
                "src": "https://img.yad2.co.il/Pic/202202/08/2_5/o/y2_5_09015_20220208141004.jpeg"
            }
        },
        "images_urls": [
            "https://img.yad2.co.il/Pic/202202/08/2_5/o/y2_1_06046_20220208140851.jpeg",
            "https://img.yad2.co.il/Pic/202202/08/2_5/o/y2_2_01213_20220208140909.jpeg",
            "https://img.yad2.co.il/Pic/202202/08/2_5/o/y2_3_08634_20220208140928.jpeg",
            "https://img.yad2.co.il/Pic/202202/08/2_5/o/y2_4_03326_20220208140940.jpeg",
            "https://img.yad2.co.il/Pic/202202/08/2_5/o/y2_5_09015_20220208141004.jpeg"
        ],
        "images_count": 5,
        "merchant": true,
        "link_token": "3w0utoh9",
        "ad_highlight_type": "none",
        "highlight_text": "",
        "is_liked": 0,
        "like_count": 0,
        "line_1_text_color": "",
        "line_2_text_color": "808080",
        "can_change_layout": 1,
        "default_layout": "system",
        "remove_on_unlike": false,
        "video_url": null,
        "mp4_video_url": null,
        "updated_at": "עודכן היום",
        "price": "2,850,000 ₪",
        "currency": "₪",
        "uid": "AkOXPs/LFb0WVcOk+y1sRTWA9ifMkoEwgiugfv4E2Zw=",
        "search_text": "דירה תיווך מכירה חדרים ב גבעתיים , שינקין , המעלות $HomeNum קומה $Floor_text מתוך $TotalFloor_text קומות. $FurnitureInfo ברח המעלות דירת 4.5 חדרים 81 מטר 8  מטר  מרפסת בבניין שעבר תמא 38 1 המרפסת  צופה לשביל  שקט וירוק  חניה רובוטית  משותפת לכל הדיריים  מיקום מעולה דודי דירה 4 $Floor_text $TotalFloor_text $Amudim_text $Furniture_text $PandorDoors_text מיזוג מעלית חניה סורגים גישה לנכים אזור רמת גן וגבעתיים $Immediate_text ממ\"ד מרפסת $storeroom_text $sunpatio_text ₪ $Meshupatz_text $Porch_text $yehidatdiur_text במצב שמור הצג רחוב $show_home_text $Tadiran_text עם מחיר, עם תמונה, חניה, הצג רק מושבים וקיבוצים, מעלית, מיזוג, מיזוג, סורגים, ממ\"ד, מרפסת, גישה לנכים, הצג רחוב 4 חדרים | 80 מ״ר המעלות , שינקין",
        "ad_number": 65002652,
        "customer_id": 4963215,
        "cat_id": "2",
        "subcat_id": "5",
        "record_id": 2611778,
        "date_added": "2022-02-08 13:55:00",
        "area_id": 3,
        "city": "גבעתיים",
        "neighborhood": "שינקין",
        "street": "המעלות",
        "address_home_number": null,
        "date_of_entry": "2022-04-01 00:00:00",
        "contact_name": "דודי",
        "date": "2022-04-23 15:18:13",
        "city_code": "6300",
        "id": "3w0utoh9",
        "topAreaID_text": "מרכז",
        "AreaID_text": "אזור רמת גן וגבעתיים",
        "HomeTypeID_text": "דירה",
        "Parking_text": "חניה",
        "Elevator_text": "מעלית",
        "AirConditioner_text": "מיזוג",
        "Grating_text": "סורגים",
        "mamad_text": "ממ\"ד",
        "patio_text": "מרפסת",
        "storeroom_text": "",
        "handicapped_text": "גישה לנכים",
        "Immediate_text": "",
        "PandorDoors_text": "",
        "Furniture_text": "",
        "Meshupatz_text": "",
        "sunpatio_text": "",
        "AssetClassificationID_text": "במצב שמור",
        "Rooms_text": 4,
        "Amudim_text": "",
        "yehidatdiur_text": "",
        "Tadiran_text": "",
        "show_street_text": "הצג רחוב",
        "show_home_text": "",
        "Porch_text": "",
        "currency_text": "₪",
        "square_meters": 80,
        "line_3": "סטוקהאוס נכסים",
        "merchant_name": "סטוקהאוס נכסים",
        "IsVisibleForReco": false,
        "hood_id": 1481,
        "Rooms": 4,
        "HomeTypeID": 1
    },
    {
        "order_type_id": 1,
        "background_color": "f0f0f0",
        "coordinates": {
            "latitude": "32.081892",
            "longitude": "34.811265"
        },
        "row_1": "שכונת חשמונאים, מרכז העיר א",
        "title_1": "שכונת חשמונאים, מרכז העיר א",
        "title_2": "דירה",
        "row_2": "דירה, רמת גן",
        "row_3": [
            "3 חדרים",
            "80 מ\"ר",
            "2"
        ],
        "row_4": [
            {
                "key": "rooms",
                "label": "חדרים",
                "value": 3
            },
            {
                "key": "floor",
                "label": "קומה",
                "value": 2
            },
            {
                "key": "SquareMeter",
                "label": "מ\"ר",
                "value": "80 "
            }
        ],
        "line_1": "3 חדרים",
        "line_2": "2",
        "external": [],
        "promotional_ad": 0,
        "ad_type": "ad",
        "type": "ad",
        "can_hide": 0,
        "is_hidden": 0,
        "img_url": null,
        "images": [],
        "images_urls": [
            "https://img.yad2.co.il/Pic/202204/06/2_5/o/y2_1_ZAZnwOcHkx_20220406.jpeg",
            "https://img.yad2.co.il/Pic/202204/06/2_5/o/y2_2_P61Z7bJS6v_20220406.jpeg",
            "https://img.yad2.co.il/Pic/202204/06/2_5/o/y2_3_D6gUXDTQcl_20220406.jpeg",
            "https://img.yad2.co.il/Pic/202204/06/2_5/o/y2_4_lzIzE3WX0n_20220406.jpeg",
            "https://img.yad2.co.il/Pic/202204/06/2_5/o/y2_5_lKbMuLmu8H_20220406.jpeg",
            "https://img.yad2.co.il/Pic/202204/06/2_5/o/y2_6_Eeysy7yPSF_20220406.jpeg"
        ],
        "images_count": 0,
        "merchant": true,
        "link_token": "3wyh1jnf",
        "ad_highlight_type": "none",
        "highlight_text": "",
        "is_liked": 0,
        "like_count": 0,
        "line_1_text_color": "",
        "line_2_text_color": "808080",
        "can_change_layout": 1,
        "default_layout": "system",
        "remove_on_unlike": false,
        "video_url": null,
        "mp4_video_url": null,
        "updated_at": "עודכן היום",
        "price": "2,600,000 ₪",
        "currency": "₪",
        "uid": "P+5TETyZq9flT3sMc8d0oLsnBS+A7QJrvjC8lkPHCRc=",
        "search_text": "דירה תיווך מכירה חדרים ב רמת גן , שכונת חשמונאים, מרכז העיר א , $Address $HomeNum קומה $Floor_text מתוך $TotalFloor_text קומות. $FurnitureInfo פריים לוקיישן \nבבנין צפוי להיות תהליך של פינוי בינוי\nהמיקום קרוב לתחנת רכבת עתידית\nנמצא בסמטה שקטה ללא מוצא אייל קליין דירה 3 $Floor_text $TotalFloor_text עמודים $Furniture_text $PandorDoors_text מיזוג $Elevator_text $Parking_text $Grating_text $handicapped_text אזור רמת גן וגבעתיים מיידי $mamad_text מרפסת $storeroom_text $sunpatio_text ₪ משופצת $Porch_text $yehidatdiur_text משופץ $show_street_text $show_home_text $Tadiran_text עם מחיר, הצג רק מושבים וקיבוצים, מיזוג, מיזוג, מרפסת, מיידי, משופצת, עמודים 3 חדרים | 80 מ״ר | 2 , שכונת חשמונאים, מרכז העיר א",
        "ad_number": 63371272,
        "customer_id": 5458326,
        "cat_id": "2",
        "subcat_id": "5",
        "record_id": 2642129,
        "date_added": "2022-04-06 12:49:12",
        "area_id": 3,
        "city": "רמת גן",
        "neighborhood": "שכונת חשמונאים, מרכז העיר א",
        "street": null,
        "address_home_number": null,
        "date_of_entry": "2022-04-06 00:00:00",
        "contact_name": "אייל קליין",
        "date": "2022-04-23 16:00:47",
        "city_code": "8600",
        "id": "3wyh1jnf",
        "topAreaID_text": "מרכז",
        "AreaID_text": "אזור רמת גן וגבעתיים",
        "HomeTypeID_text": "דירה",
        "Parking_text": "",
        "Elevator_text": "",
        "AirConditioner_text": "מיזוג",
        "Grating_text": "",
        "mamad_text": "",
        "patio_text": "מרפסת",
        "storeroom_text": "",
        "handicapped_text": "",
        "Immediate_text": "מיידי",
        "PandorDoors_text": "",
        "Furniture_text": "",
        "Meshupatz_text": "משופצת",
        "sunpatio_text": "",
        "AssetClassificationID_text": "משופץ",
        "Rooms_text": 3,
        "Amudim_text": "עמודים",
        "yehidatdiur_text": "",
        "Tadiran_text": "",
        "show_street_text": "",
        "show_home_text": "",
        "Porch_text": "",
        "currency_text": "₪",
        "square_meters": 80,
        "address_more": "נכס מניב פרטים בטלפון",
        "line_3": "אייל קליין-איתך עד הבית",
        "merchant_name": "אייל קליין-איתך עד הבית",
        "office_logo_url": "//img.yad2.co.il/Pic/TivMiniSite/7cbf59e5-9e2a-4a3b-87d3-73e3b8c2e584.jpg?t=1650718880137",
        "office_about": ",משרדנו היינו משרד ותיק ומוכר בבקעת אונו , תחת ידינו יצאו לפועל עשרות רבות של עסקאות מכירה והשכרה של נכסים \r\nעי גישה מקצועית איכותית ומקיפה ובאווירה לבבית אנחנו משלבים בסינרגיה בין הצורך להיות ראשונים תמיד לבין האיזון העדין של שירות לקוחות ממדרגה ראשונה\r\nנשמח להמשיך ולתמוך וללוות לקוחות חדשים ,מנקודת המכירה ועד רגע העע חתימת החוזה הנכסף.\r\nמשרדנו עובד בשתפ מלא ,עם כל משרדי התיווך בסביבה ,ובשיתוף בעלי מקצוע כגון ,יועצי משכנתאות , אדריכלים ,עורכי דין מומחים ועוד",
        "IsVisibleForReco": false,
        "hood_id": 1477,
        "Rooms": 3,
        "HomeTypeID": 1
    },
    {
        "order_type_id": 1,
        "background_color": "f0f0f0",
        "coordinates": {
            "latitude": "32.0782863461538",
            "longitude": "34.8077630384615"
        },
        "row_1": "המעורר",
        "title_1": "המעורר",
        "title_2": "דירה",
        "row_2": "דירה, בורוכוב, גבעתיים",
        "row_3": [
            "3 חדרים",
            "85 מ\"ר",
            "1"
        ],
        "row_4": [
            {
                "key": "rooms",
                "label": "חדרים",
                "value": 3
            },
            {
                "key": "floor",
                "label": "קומה",
                "value": 1
            },
            {
                "key": "SquareMeter",
                "label": "מ\"ר",
                "value": "85 "
            }
        ],
        "line_1": "3 חדרים",
        "line_2": "1",
        "external": [],
        "promotional_ad": 0,
        "ad_type": "ad",
        "type": "ad",
        "can_hide": 0,
        "is_hidden": 0,
        "img_url": "https://img.yad2.co.il/Pic/202012/16/2_5/o/o2_5_1_07393_20201216141210.jpg",
        "images": {
            "Image1": {
                "src": "https://img.yad2.co.il/Pic/202012/16/2_5/o/o2_5_1_07393_20201216141210.jpg"
            },
            "Image2": {
                "src": "https://img.yad2.co.il/Pic/202012/16/2_5/o/o2_5_2_04429_20201216141219.jpg"
            },
            "Image3": {
                "src": "https://img.yad2.co.il/Pic/202012/16/2_5/o/o2_5_3_06454_20201216141224.jpg"
            },
            "Image4": {
                "src": "https://img.yad2.co.il/Pic/202012/16/2_5/o/o2_5_4_09663_20201216141213.jpg"
            },
            "Image5": {
                "src": "https://img.yad2.co.il/Pic/202012/16/2_5/o/o2_5_5_01915_20201216141223.jpg"
            }
        },
        "images_urls": [
            "https://img.yad2.co.il/Pic/202012/16/2_5/o/o2_5_1_07393_20201216141210.jpg",
            "https://img.yad2.co.il/Pic/202012/16/2_5/o/o2_5_2_04429_20201216141219.jpg",
            "https://img.yad2.co.il/Pic/202012/16/2_5/o/o2_5_3_06454_20201216141224.jpg",
            "https://img.yad2.co.il/Pic/202012/16/2_5/o/o2_5_4_09663_20201216141213.jpg",
            "https://img.yad2.co.il/Pic/202012/16/2_5/o/o2_5_5_01915_20201216141223.jpg"
        ],
        "images_count": 5,
        "merchant": true,
        "link_token": "9u37x2p7",
        "ad_highlight_type": "none",
        "highlight_text": "",
        "is_liked": 0,
        "like_count": 0,
        "line_1_text_color": "",
        "line_2_text_color": "808080",
        "can_change_layout": 1,
        "default_layout": "system",
        "remove_on_unlike": false,
        "video_url": null,
        "mp4_video_url": null,
        "updated_at": "עודכן היום",
        "price": "2,690,000 ₪",
        "currency": "₪",
        "uid": "4XF4oiaqvZZTtAsBeZaw3w==",
        "search_text": "דירה תיווך מכירה חדרים ב גבעתיים , בורוכוב , המעורר $HomeNum קומה $Floor_text מתוך $TotalFloor_text קומות. $FurnitureInfo $Remark איציק דירה 3 $Floor_text $TotalFloor_text $Amudim_text $Furniture_text $PandorDoors_text מיזוג $Elevator_text $Parking_text $Grating_text $handicapped_text אזור רמת גן וגבעתיים $Immediate_text $mamad_text מרפסת $storeroom_text $sunpatio_text ₪ משופצת $Porch_text $yehidatdiur_text משופץ הצג רחוב $show_home_text $Tadiran_text עם מחיר, עם תמונה, הצג רק מושבים וקיבוצים, מיזוג, מיזוג, מרפסת, משופצת, הצג רחוב 3 חדרים | 85 מ״ר | 1 המעורר , בורוכוב",
        "ad_number": 44916949,
        "customer_id": 694395,
        "cat_id": "2",
        "subcat_id": "5",
        "record_id": 2405496,
        "date_added": "2020-12-16 14:47:47",
        "area_id": 3,
        "city": "גבעתיים",
        "neighborhood": "בורוכוב",
        "street": "המעורר",
        "address_home_number": null,
        "date_of_entry": null,
        "contact_name": "איציק",
        "date": "2022-04-23 16:39:34",
        "city_code": "6300",
        "id": "9u37x2p7",
        "topAreaID_text": "מרכז",
        "AreaID_text": "אזור רמת גן וגבעתיים",
        "HomeTypeID_text": "דירה",
        "Parking_text": "",
        "Elevator_text": "",
        "AirConditioner_text": "מיזוג",
        "Grating_text": "",
        "mamad_text": "",
        "patio_text": "מרפסת",
        "storeroom_text": "",
        "handicapped_text": "",
        "Immediate_text": "",
        "PandorDoors_text": "",
        "Furniture_text": "",
        "Meshupatz_text": "משופצת",
        "sunpatio_text": "",
        "AssetClassificationID_text": "משופץ",
        "Rooms_text": 3,
        "Amudim_text": "",
        "yehidatdiur_text": "",
        "Tadiran_text": "",
        "show_street_text": "הצג רחוב",
        "show_home_text": "",
        "Porch_text": "",
        "currency_text": "₪",
        "square_meters": 85,
        "line_3": "נכסים street",
        "merchant_name": "נכסים street",
        "office_logo_url": "//img.yad2.co.il/Pic/TivMiniSite/logo100_2_7_749070_20190108200135-l.jpg?t=1650721187614",
        "office_about": "חברת נדל\"ן שמתמחה בשיווק ומכירת דירות יד 2 בערים ת\"א גבעתיים רמת גן וחולון.חברה ששמה דגש על השירות האישי והתאמת הדירה בדיוק לצרכי הלקוח.\r\nאם זה למגורים או להשקעה.",
        "IsVisibleForReco": false,
        "hood_id": 355,
        "Rooms": 3,
        "HomeTypeID": 1
    },
    {
        "order_type_id": 3,
        "background_color": "fef0a9",
        "coordinates": {
            "latitude": "32.081892",
            "longitude": "34.811265"
        },
        "row_1": "שכונת חשמונאים, מרכז העיר א",
        "title_1": "שכונת חשמונאים, מרכז העיר א",
        "title_2": "דירה",
        "row_2": "דירה, רמת גן",
        "row_3": [
            "4 חדרים",
            "80 מ\"ר",
            "1"
        ],
        "row_4": [
            {
                "key": "rooms",
                "label": "חדרים",
                "value": 4
            },
            {
                "key": "floor",
                "label": "קומה",
                "value": 1
            },
            {
                "key": "SquareMeter",
                "label": "מ\"ר",
                "value": "80 "
            }
        ],
        "line_1": "4 חדרים",
        "line_2": "1",
        "external": [],
        "promotional_ad": 0,
        "ad_type": "ad",
        "type": "ad",
        "can_hide": 0,
        "is_hidden": 0,
        "img_url": null,
        "images": [],
        "images_urls": [
            "https://img.yad2.co.il/Pic/202203/17/2_5/o/y2_1_ec_8Pdz73P_20220317.jpg"
        ],
        "images_count": 0,
        "merchant": true,
        "link_token": "bdeykr94",
        "ad_highlight_type": "yellow",
        "highlight_text": "בלעדי",
        "is_liked": 0,
        "like_count": 0,
        "line_1_text_color": "",
        "line_2_text_color": "808080",
        "can_change_layout": 1,
        "default_layout": "system",
        "remove_on_unlike": false,
        "video_url": null,
        "mp4_video_url": null,
        "updated_at": "עודכן היום",
        "price": "2,790,000 ₪",
        "currency": "₪",
        "uid": "RGZO9aSdALNj0aX6UJ1KVc/1XGw5WubnhkTLWgiJWqw=",
        "search_text": "דירה תיווך מכירה חדרים ב רמת גן , שכונת חשמונאים, מרכז העיר א , $Address $HomeNum קומה $Floor_text מתוך $TotalFloor_text קומות. $FurnitureInfo מיקום מעולה בשכונה - יציאות נוחות לכיוון תל אביב ונתיבי איילון. משופצת מלפני שנתיים כולל אינטלציה וחשמל. צפון מזרח - קומה ראשונה מעלית. חניה משותפת בהסדר של שנים בין השכנים. מושלמת למגורים והשקעה. עורפית ושקטה מאוד. מוארת. רישום נקי. מרפסת מקורה בסלון (יש תמונה). שירותים כפולים . פוטנציאל השבחה גדול בעתיד. צח דירה 4 $Floor_text $TotalFloor_text עמודים ריהוט $PandorDoors_text מיזוג מעלית חניה סורגים גישה לנכים אזור רמת גן וגבעתיים $Immediate_text $mamad_text מרפסת $storeroom_text $sunpatio_text ₪ משופצת $Porch_text $yehidatdiur_text משופץ $show_street_text $show_home_text מזגן תדיראן עם מחיר, חניה, הצג רק מושבים וקיבוצים, מעלית, מיזוג, מיזוג, סורגים, מרפסת, גישה לנכים, ריהוט, משופצת, בבלעדיות, עמודים, מזגן תדיראן 4 חדרים | 80 מ״ר | 1 , שכונת חשמונאים, מרכז העיר א",
        "ad_number": 59936704,
        "customer_id": 7145553,
        "cat_id": "2",
        "subcat_id": "5",
        "record_id": 2632317,
        "date_added": "2022-03-17 11:34:29",
        "area_id": 3,
        "city": "רמת גן",
        "neighborhood": "שכונת חשמונאים, מרכז העיר א",
        "street": null,
        "address_home_number": null,
        "date_of_entry": "2022-04-14 00:00:00",
        "contact_name": "צח",
        "date": "2022-04-23 17:18:18",
        "city_code": "8600",
        "id": "bdeykr94",
        "topAreaID_text": "מרכז",
        "AreaID_text": "אזור רמת גן וגבעתיים",
        "HomeTypeID_text": "דירה",
        "Parking_text": "חניה",
        "Elevator_text": "מעלית",
        "AirConditioner_text": "מיזוג",
        "Grating_text": "סורגים",
        "mamad_text": "",
        "patio_text": "מרפסת",
        "storeroom_text": "",
        "handicapped_text": "גישה לנכים",
        "Immediate_text": "",
        "PandorDoors_text": "",
        "Furniture_text": "ריהוט",
        "Meshupatz_text": "משופצת",
        "sunpatio_text": "",
        "AssetClassificationID_text": "משופץ",
        "Rooms_text": 4,
        "Amudim_text": "עמודים",
        "yehidatdiur_text": "",
        "Tadiran_text": "מזגן תדיראן",
        "show_street_text": "",
        "show_home_text": "",
        "Porch_text": "",
        "currency_text": "₪",
        "square_meters": 80,
        "line_3": "מור נכסים",
        "merchant_name": "מור נכסים",
        "IsVisibleForReco": false,
        "hood_id": 1477,
        "Rooms": 4,
        "HomeTypeID": 1
    },
    {
        "order_type_id": 1,
        "background_color": "f0f0f0",
        "coordinates": {
            "latitude": "32.0807839677419",
            "longitude": "34.8036889354839"
        },
        "row_1": "הראשונים",
        "title_1": "הראשונים",
        "title_2": "דירה",
        "row_2": "דירה, שכונת הראשונים, רמת גן",
        "row_3": [
            "4 חדרים",
            "97 מ\"ר",
            "3"
        ],
        "row_4": [
            {
                "key": "rooms",
                "label": "חדרים",
                "value": 4
            },
            {
                "key": "floor",
                "label": "קומה",
                "value": 3
            },
            {
                "key": "SquareMeter",
                "label": "מ\"ר",
                "value": "97 "
            }
        ],
        "line_1": "4 חדרים",
        "line_2": "3",
        "external": [],
        "promotional_ad": 0,
        "ad_type": "ad",
        "type": "ad",
        "can_hide": 0,
        "is_hidden": 0,
        "img_url": null,
        "images": [],
        "images_urls": [
            "https://img.yad2.co.il/Pic/202201/04/2_5/o/y2_1_pUGg5XAG2u_20220104.jpg"
        ],
        "images_count": 0,
        "merchant": true,
        "link_token": "ca1a9zpi",
        "ad_highlight_type": "none",
        "highlight_text": "",
        "is_liked": 0,
        "like_count": 0,
        "line_1_text_color": "",
        "line_2_text_color": "808080",
        "can_change_layout": 1,
        "default_layout": "system",
        "remove_on_unlike": false,
        "video_url": null,
        "mp4_video_url": null,
        "updated_at": "עודכן היום",
        "price": "2,850,000 ₪",
        "currency": "₪",
        "uid": "xZb5GqkJHKH6OS2TztpIgA==",
        "search_text": "דירה תיווך מכירה חדרים ב רמת גן , שכונת הראשונים , הראשונים $HomeNum קומה $Floor_text מתוך $TotalFloor_text קומות. $FurnitureInfo בלעדית למשרדנו! דירה קיימת לפני תחילת עבודות תמא 38 חיזוק ותוספת. \nהדירה כיום 3 חד' משופצים 85 מ\"ר.\nמתחילים בחודש אפריל - יתווסף 12 מ\"ר ממ\"ד, מעלית ומחסן.\nעסקה מעולה! אבירן דירה 4 $Floor_text $TotalFloor_text עמודים $Furniture_text $PandorDoors_text מיזוג מעלית $Parking_text $Grating_text $handicapped_text אזור רמת גן וגבעתיים $Immediate_text ממ\"ד $patio_text מחסן $sunpatio_text ₪ משופצת $Porch_text $yehidatdiur_text משופץ הצג רחוב $show_home_text $Tadiran_text עם מחיר, הצג רק מושבים וקיבוצים, מעלית, מיזוג, מיזוג, ממ\"ד, מחסן, משופצת, עמודים, הצג רחוב 4 חדרים | 97 מ״ר | 3 הראשונים ב , שכונת הראשונים",
        "ad_number": 79794472,
        "customer_id": 198398,
        "cat_id": "2",
        "subcat_id": "5",
        "record_id": 2593316,
        "date_added": "2022-01-04 16:17:01",
        "area_id": 3,
        "city": "רמת גן",
        "neighborhood": "שכונת הראשונים",
        "street": "הראשונים",
        "address_home_number": null,
        "date_of_entry": "2022-09-15 00:00:00",
        "contact_name": "אבירן",
        "date": "2022-04-23 16:18:32",
        "city_code": "8600",
        "id": "ca1a9zpi",
        "topAreaID_text": "מרכז",
        "AreaID_text": "אזור רמת גן וגבעתיים",
        "HomeTypeID_text": "דירה",
        "Parking_text": "",
        "Elevator_text": "מעלית",
        "AirConditioner_text": "מיזוג",
        "Grating_text": "",
        "mamad_text": "ממ\"ד",
        "patio_text": "",
        "storeroom_text": "מחסן",
        "handicapped_text": "",
        "Immediate_text": "",
        "PandorDoors_text": "",
        "Furniture_text": "",
        "Meshupatz_text": "משופצת",
        "sunpatio_text": "",
        "AssetClassificationID_text": "משופץ",
        "Rooms_text": 4,
        "Amudim_text": "עמודים",
        "yehidatdiur_text": "",
        "Tadiran_text": "",
        "show_street_text": "הצג רחוב",
        "show_home_text": "",
        "Porch_text": "",
        "currency_text": "₪",
        "square_meters": 97,
        "line_3": "אפיקי מרום",
        "merchant_name": "אפיקי מרום",
        "office_logo_url": "//img.yad2.co.il/Pic/TivMiniSite/logo100_5_1_712316_20191110171129-l.jpg?t=1650719925685",
        "office_about": "מחפשים נכס בגבול ר\"ג-גבעתיים-ת\"א הגעת למקום הנכון!\r\nאנו משרד תיווך בוטיק,\r\nבעל מוניטין משנת 1996 ממוקם בלב שכונת הראשונים ברמת גן, והפך להיות לחלק בלתי נפרד \"ממשפחת הראשונים\",\r\nהמשרד נמצא על התפר שבין ר\"ג , שכונת בורוכוב בגבעתיים, ונחלת-יצחק שבתל אביב.\r\n\r\nאנו מתמחים בשיווק פרויקטים חדשים בלעדיים, מכירה והשכרה של דירות יד שנייה, וכן ייעוץ והדרכה לקידום עסקאות תמ\"א 38 ופינוי בינוי.\r\n\r\nמשרדנו דוגל במתן שרות אישי ומסור, מקצועי ויעיל הן לרוכשים והן לניהול הנכסים שבידנו. כאשר הדירות הבלעדיות שברשותנו נמכרות תוך זמן קצר.\r\n\r\nבמשרדנו חוג לקוחות קבוע של משקיעים ובעלי נכסים המשרת את האזור כבר 20 שנה.\r\nאם את/ה לפני מכירת דירה אתה מוזמן לפנות אלינו לייעוץ מקצועי ללא עלות כספית.",
        "IsVisibleForReco": false,
        "hood_id": 1647,
        "Rooms": 4,
        "HomeTypeID": 1
    },
    {
        "order_type_id": 1,
        "background_color": "f0f0f0",
        "coordinates": {
            "latitude": "32.0887863333333",
            "longitude": "34.8052451111111"
        },
        "row_1": "אביגיל",
        "title_1": "אביגיל",
        "title_2": "דירה",
        "row_2": "דירה, חרוזים, רמת גן",
        "row_3": [
            "3 חדרים",
            "70 מ\"ר",
            "6"
        ],
        "row_4": [
            {
                "key": "rooms",
                "label": "חדרים",
                "value": 3
            },
            {
                "key": "floor",
                "label": "קומה",
                "value": 6
            },
            {
                "key": "SquareMeter",
                "label": "מ\"ר",
                "value": "70 "
            }
        ],
        "line_1": "3 חדרים",
        "line_2": "6",
        "external": [],
        "promotional_ad": 0,
        "ad_type": "ad",
        "type": "ad",
        "can_hide": 0,
        "is_hidden": 0,
        "img_url": null,
        "images": [],
        "images_urls": [
            "https://img.yad2.co.il/Pic/202111/17/2_5/o/y2_1_3l9vLZGqEs_20211117.jpeg",
            "https://img.yad2.co.il/Pic/202111/17/2_5/o/y2_2_TsKUHraAvE_20211117.jpeg"
        ],
        "images_count": 0,
        "merchant": true,
        "link_token": "huu7t92u",
        "ad_highlight_type": "none",
        "highlight_text": "",
        "is_liked": 0,
        "like_count": 0,
        "line_1_text_color": "",
        "line_2_text_color": "808080",
        "can_change_layout": 1,
        "default_layout": "system",
        "remove_on_unlike": false,
        "video_url": null,
        "mp4_video_url": null,
        "updated_at": "עודכן היום",
        "price": "2,790,000 ₪",
        "currency": "₪",
        "uid": "+LiGNeYFhboTyKlQ5+0T66DtzmZ7DNGDPCvsnvRc8Fk=",
        "search_text": "דירה תיווך מכירה חדרים ב רמת גן , חרוזים , אביגיל $HomeNum קומה $Floor_text מתוך $TotalFloor_text קומות. $FurnitureInfo דירה בבנין חדש בן כ4 שנים בלב שכונת חרוזים המבוקשת, קלאסית להשקעה או למגורים. טינר בן דוד דירה 3 $Floor_text $TotalFloor_text $Amudim_text $Furniture_text $PandorDoors_text מיזוג מעלית חניה $Grating_text גישה לנכים אזור רמת גן וגבעתיים מיידי ממ\"ד מרפסת $storeroom_text $sunpatio_text ₪ משופצת $Porch_text $yehidatdiur_text חדש (גרו בנכס) הצג רחוב $show_home_text מזגן תדיראן עם מחיר, חניה, הצג רק מושבים וקיבוצים, מעלית, מיזוג, מיזוג, ממ\"ד, מרפסת, גישה לנכים, מיידי, משופצת, מזגן תדיראן, הצג רחוב 3 חדרים | 70 מ״ר | 6 אביגיל , חרוזים",
        "ad_number": 69434241,
        "customer_id": 3888433,
        "cat_id": "2",
        "subcat_id": "5",
        "record_id": 2568271,
        "date_added": "2021-11-17 19:52:43",
        "area_id": 3,
        "city": "רמת גן",
        "neighborhood": "חרוזים",
        "street": "אביגיל",
        "address_home_number": null,
        "date_of_entry": "2022-01-24 00:00:00",
        "contact_name": "טינר בן דוד",
        "date": "2022-04-23 17:06:25",
        "city_code": "8600",
        "id": "huu7t92u",
        "topAreaID_text": "מרכז",
        "AreaID_text": "אזור רמת גן וגבעתיים",
        "HomeTypeID_text": "דירה",
        "Parking_text": "חניה",
        "Elevator_text": "מעלית",
        "AirConditioner_text": "מיזוג",
        "Grating_text": "",
        "mamad_text": "ממ\"ד",
        "patio_text": "מרפסת",
        "storeroom_text": "",
        "handicapped_text": "גישה לנכים",
        "Immediate_text": "מיידי",
        "PandorDoors_text": "",
        "Furniture_text": "",
        "Meshupatz_text": "משופצת",
        "sunpatio_text": "",
        "AssetClassificationID_text": "חדש (גרו בנכס)",
        "Rooms_text": 3,
        "Amudim_text": "",
        "yehidatdiur_text": "",
        "Tadiran_text": "מזגן תדיראן",
        "show_street_text": "הצג רחוב",
        "show_home_text": "",
        "Porch_text": "",
        "currency_text": "₪",
        "square_meters": 70,
        "line_3": "Elita One",
        "merchant_name": "Elita One",
        "office_logo_url": "//img.yad2.co.il/Pic/TivMiniSite/logo100_2_7_721529_20190522090529-l.jpg?t=1650722804224",
        "office_about": "חברת הנדל\"ן Elita One בשיתוף חברתו של תום הרוש - מבינים אנשים. מומחים בנדל\"ן, קמו, כדי לתת מענה לכמה שיותר אנשים בכל תחום של יעוץ נדל\"ן , לסייע ללקוח פוטנציאלי לקבל החלטה שתשרת באופן הטוב ביותר, את האינטרסים שלו.לשלב את הרוחניות, בתוך עולם העסקים, בתחום תיווך הנדל\"ן בפרטאם אתם מכירים אנשים שרוצים למכור, לקנות, לשכור או להשכיר את הנכס שלהם, נשמח מאוד לייצר פתרון!\n\nאחרי מאות עסקאות וניסיון של כעשור בתחום הנדל\"ן והתמחות ספציפית ברמת גן וגבעתיים, אנחנו בטוחים שנצליח להשיג לכם את התוצאה המקסימלית.",
        "IsVisibleForReco": false,
        "hood_id": 327,
        "Rooms": 3,
        "HomeTypeID": 1
    },
    {
        "order_type_id": 1,
        "background_color": "f0f0f0",
        "coordinates": {
            "latitude": "32.081422",
            "longitude": "34.804167"
        },
        "row_1": "שכונת הראשונים",
        "title_1": "שכונת הראשונים",
        "title_2": "דירה",
        "row_2": "דירה, רמת גן",
        "row_3": [
            "4 חדרים",
            "97 מ\"ר",
            "3"
        ],
        "row_4": [
            {
                "key": "rooms",
                "label": "חדרים",
                "value": 4
            },
            {
                "key": "floor",
                "label": "קומה",
                "value": 3
            },
            {
                "key": "SquareMeter",
                "label": "מ\"ר",
                "value": "97 "
            }
        ],
        "line_1": "4 חדרים",
        "line_2": "3",
        "external": [],
        "promotional_ad": 0,
        "ad_type": "ad",
        "type": "ad",
        "can_hide": 0,
        "is_hidden": 0,
        "img_url": "https://img.yad2.co.il/Pic/202112/26/2_5/o/y2_1_01413_20211226113133.jpeg",
        "images": {
            "Image1": {
                "src": "https://img.yad2.co.il/Pic/202112/26/2_5/o/y2_1_01413_20211226113133.jpeg"
            },
            "Image2": {
                "src": "https://img.yad2.co.il/Pic/202112/26/2_5/o/y2_2_02173_20211226113132.jpeg"
            },
            "Image3": {
                "src": "https://img.yad2.co.il/Pic/202112/26/2_5/o/y2_3_03908_20211226113138.jpeg"
            },
            "Image4": {
                "src": "https://img.yad2.co.il/Pic/202112/26/2_5/o/y2_4_03313_20211226113142.jpeg"
            }
        },
        "images_urls": [
            "https://img.yad2.co.il/Pic/202112/26/2_5/o/y2_1_01413_20211226113133.jpeg",
            "https://img.yad2.co.il/Pic/202112/26/2_5/o/y2_2_02173_20211226113132.jpeg",
            "https://img.yad2.co.il/Pic/202112/26/2_5/o/y2_3_03908_20211226113138.jpeg",
            "https://img.yad2.co.il/Pic/202112/26/2_5/o/y2_4_03313_20211226113142.jpeg"
        ],
        "images_count": 4,
        "merchant": true,
        "link_token": "iatca0mn",
        "ad_highlight_type": "none",
        "highlight_text": "בלעדי",
        "is_liked": 0,
        "like_count": 0,
        "line_1_text_color": "",
        "line_2_text_color": "808080",
        "can_change_layout": 1,
        "default_layout": "system",
        "remove_on_unlike": false,
        "video_url": null,
        "mp4_video_url": null,
        "updated_at": "עודכן היום",
        "price": "2,850,000 ₪",
        "currency": "₪",
        "uid": "J6LfiW9FYHS8Qn8BAYFg5Q==",
        "search_text": "דירה תיווך מכירה חדרים ב רמת גן , שכונת הראשונים , $Address $HomeNum קומה $Floor_text מתוך $TotalFloor_text קומות. $FurnitureInfo בלעדיות חדשה, בלב שכונת הראשונים ברמת גן גבול בורוכוב גבעתיים, \r\nדירה לפני תחילת עבודות בפרוייקט תמא 38/1\r\n{תוספת ובנייה על הקיים}\r\nהדירה היום בשטח של 85 מ\"ר משופצת\r\nמקבלת תוספת 12 מ\"ר{ממ\"ד}+ מחסן\r\n3 כיווני אוויר  מלאים!! רובי דירה 4 $Floor_text $TotalFloor_text עמודים $Furniture_text $PandorDoors_text מיזוג מעלית $Parking_text $Grating_text $handicapped_text אזור רמת גן וגבעתיים $Immediate_text ממ\"ד $patio_text מחסן $sunpatio_text ₪ משופצת $Porch_text $yehidatdiur_text משופץ $show_street_text $show_home_text $Tadiran_text עם מחיר, עם תמונה, הצג רק מושבים וקיבוצים, מעלית, מיזוג, מיזוג, ממ\"ד, מחסן, משופצת, בבלעדיות, עמודים 4 חדרים | 97 מ״ר | 3 , שכונת הראשונים",
        "ad_number": 85496636,
        "customer_id": 198398,
        "cat_id": "2",
        "subcat_id": "5",
        "record_id": 2587936,
        "date_added": "2021-12-26 11:29:35",
        "area_id": 3,
        "city": "רמת גן",
        "neighborhood": "שכונת הראשונים",
        "street": null,
        "address_home_number": null,
        "date_of_entry": "2022-10-01 00:00:00",
        "contact_name": "רובי",
        "date": "2022-04-23 14:45:35",
        "city_code": "8600",
        "id": "iatca0mn",
        "topAreaID_text": "מרכז",
        "AreaID_text": "אזור רמת גן וגבעתיים",
        "HomeTypeID_text": "דירה",
        "Parking_text": "",
        "Elevator_text": "מעלית",
        "AirConditioner_text": "מיזוג",
        "Grating_text": "",
        "mamad_text": "ממ\"ד",
        "patio_text": "",
        "storeroom_text": "מחסן",
        "handicapped_text": "",
        "Immediate_text": "",
        "PandorDoors_text": "",
        "Furniture_text": "",
        "Meshupatz_text": "משופצת",
        "sunpatio_text": "",
        "AssetClassificationID_text": "משופץ",
        "Rooms_text": 4,
        "Amudim_text": "עמודים",
        "yehidatdiur_text": "",
        "Tadiran_text": "",
        "show_street_text": "",
        "show_home_text": "",
        "Porch_text": "",
        "currency_text": "₪",
        "square_meters": 97,
        "line_3": "אפיקי מרום",
        "merchant_name": "אפיקי מרום",
        "office_logo_url": "//img.yad2.co.il/Pic/TivMiniSite/logo100_5_1_712316_20191110171129-l.jpg?t=1650714349625",
        "office_about": "מחפשים נכס בגבול ר\"ג-גבעתיים-ת\"א הגעת למקום הנכון!\r\nאנו משרד תיווך בוטיק,\r\nבעל מוניטין משנת 1996 ממוקם בלב שכונת הראשונים ברמת גן, והפך להיות לחלק בלתי נפרד \"ממשפחת הראשונים\",\r\nהמשרד נמצא על התפר שבין ר\"ג , שכונת בורוכוב בגבעתיים, ונחלת-יצחק שבתל אביב.\r\n\r\nאנו מתמחים בשיווק פרויקטים חדשים בלעדיים, מכירה והשכרה של דירות יד שנייה, וכן ייעוץ והדרכה לקידום עסקאות תמ\"א 38 ופינוי בינוי.\r\n\r\nמשרדנו דוגל במתן שרות אישי ומסור, מקצועי ויעיל הן לרוכשים והן לניהול הנכסים שבידנו. כאשר הדירות הבלעדיות שברשותנו נמכרות תוך זמן קצר.\r\n\r\nבמשרדנו חוג לקוחות קבוע של משקיעים ובעלי נכסים המשרת את האזור כבר 20 שנה.\r\nאם את/ה לפני מכירת דירה אתה מוזמן לפנות אלינו לייעוץ מקצועי ללא עלות כספית.",
        "IsVisibleForReco": false,
        "hood_id": 1647,
        "Rooms": 4,
        "HomeTypeID": 1
    },
    {
        "order_type_id": 1,
        "background_color": "f0f0f0",
        "coordinates": {
            "latitude": "32.081422",
            "longitude": "34.804167"
        },
        "row_1": "שכונת הראשונים",
        "title_1": "שכונת הראשונים",
        "title_2": "דירה",
        "row_2": "דירה, רמת גן",
        "row_3": [
            "4 חדרים",
            "90 מ\"ר",
            "4"
        ],
        "row_4": [
            {
                "key": "rooms",
                "label": "חדרים",
                "value": 4
            },
            {
                "key": "floor",
                "label": "קומה",
                "value": 4
            },
            {
                "key": "SquareMeter",
                "label": "מ\"ר",
                "value": "90 "
            }
        ],
        "line_1": "4 חדרים",
        "line_2": "4",
        "external": [],
        "promotional_ad": 0,
        "ad_type": "ad",
        "type": "ad",
        "can_hide": 0,
        "is_hidden": 0,
        "img_url": null,
        "images": [],
        "images_urls": [
            "https://img.yad2.co.il/Pic/202106/29/2_5/o/y2_1_8aUKuS3NPD_20210629.jpg",
            "https://img.yad2.co.il/Pic/202106/29/2_5/o/y2_2_rJeDVB_RMu_20210629.jpg",
            "https://img.yad2.co.il/Pic/202106/29/2_5/o/y2_3_BxoALSvJ_0_20210629.jpg",
            "https://img.yad2.co.il/Pic/202106/29/2_5/o/y2_4__8rD1GxYm6_20210629.jpg"
        ],
        "images_count": 0,
        "merchant": true,
        "link_token": "q8axm842",
        "ad_highlight_type": "none",
        "highlight_text": "",
        "is_liked": 0,
        "like_count": 0,
        "line_1_text_color": "",
        "line_2_text_color": "808080",
        "can_change_layout": 1,
        "default_layout": "system",
        "remove_on_unlike": false,
        "video_url": null,
        "mp4_video_url": null,
        "updated_at": "עודכן היום",
        "price": "2,800,000 ₪",
        "currency": "₪",
        "uid": "M7kmXnoDDc3ri9SRplALMg==",
        "search_text": "דירה תיווך מכירה חדרים ב רמת גן , שכונת הראשונים , $Address $HomeNum קומה $Floor_text מתוך $TotalFloor_text קומות. $FurnitureInfo בארלוזורוב בואכה תל אביב .נושק למתחם הבורסה ולתחנת הרכבת הקלה דירת 4 חדרים עם גג מוצמד בטאבו.אפשרות ל43 מטר נוספים. משרד דירה 4 $Floor_text $TotalFloor_text עמודים $Furniture_text $PandorDoors_text מיזוג מעלית חניה $Grating_text $handicapped_text אזור רמת גן וגבעתיים מיידי $mamad_text מרפסת $storeroom_text $sunpatio_text ₪ $Meshupatz_text $Porch_text $yehidatdiur_text במצב שמור $show_street_text $show_home_text $Tadiran_text עם מחיר, חניה, הצג רק מושבים וקיבוצים, מעלית, מיזוג, מיזוג, מרפסת, מיידי, עמודים 4 חדרים | 90 מ״ר | 4 , שכונת הראשונים",
        "ad_number": 61309618,
        "customer_id": 45555,
        "cat_id": "2",
        "subcat_id": "5",
        "record_id": 2501567,
        "date_added": "2021-06-29 12:17:58",
        "area_id": 3,
        "city": "רמת גן",
        "neighborhood": "שכונת הראשונים",
        "street": null,
        "address_home_number": null,
        "date_of_entry": "2021-06-29 00:00:00",
        "contact_name": "משרד",
        "date": "2022-04-23 17:12:16",
        "city_code": "8600",
        "id": "q8axm842",
        "topAreaID_text": "מרכז",
        "AreaID_text": "אזור רמת גן וגבעתיים",
        "HomeTypeID_text": "דירה",
        "Parking_text": "חניה",
        "Elevator_text": "מעלית",
        "AirConditioner_text": "מיזוג",
        "Grating_text": "",
        "mamad_text": "",
        "patio_text": "מרפסת",
        "storeroom_text": "",
        "handicapped_text": "",
        "Immediate_text": "מיידי",
        "PandorDoors_text": "",
        "Furniture_text": "",
        "Meshupatz_text": "",
        "sunpatio_text": "",
        "AssetClassificationID_text": "במצב שמור",
        "Rooms_text": 4,
        "Amudim_text": "עמודים",
        "yehidatdiur_text": "",
        "Tadiran_text": "",
        "show_street_text": "",
        "show_home_text": "",
        "Porch_text": "",
        "currency_text": "₪",
        "square_meters": 90,
        "address_more": "גג מוצמד בטאבו",
        "line_3": "א.ל.ע.ד נכסים",
        "merchant_name": "א.ל.ע.ד נכסים",
        "office_logo_url": "//img.yad2.co.il/Pic/TivMiniSite/logo2_5_9461_20161204101254.jpg?t=1650723171410",
        "office_about": "א.ל.ע.ד נכסים מתמחה מזה כ  20 שנה במכירה קניה השכרה של דירות ושיווק פרוייקטים בתחום הנדל\"ן באיזור המרכז. \r\nמקימי החברה שמו להם כיעד להביא גישה מקצועית, ורמת שירות על פי סטנדרטים גבוהים של עבודה תוך התאמה אישית לצורכי הלקוח. \r\nהתובנה שהלקוחות הם המעיין ממנו אנו רווים מחייבת אותנו לאמינות ונאמנות מעל לכל. \r\n\"דירה לא קונים כל יום\"  קניית דירה זו העיסקה הגדולה בחייו של אדם והוכח שאין מוסד מתאים שמלמד איך לקנות דירה, ולכן קניית דירה מחייבת ליווי מקצועי, הליכה במסלול נכון, סבלנות, ניתוח נכון של מצב השוק בתקופת זמן נתונה וניצול הזדמנויות. \r\nהמוטו שלנו הוא להסתכל דרך עיניו של הלקוח, ולהיות רגישים לצרכיו, ותוך הבנה שהזמן של כולנו יקר, דיוק מירבי וחדות מקצועית שתביא את הלקוח להגשמת חלומו",
        "IsVisibleForReco": false,
        "hood_id": 1647,
        "Rooms": 4,
        "HomeTypeID": 1
    },
    {
        "order_type_id": 3,
        "background_color": "fef0a9",
        "coordinates": {
            "latitude": "32.0808449166667",
            "longitude": "34.8068744166667"
        },
        "row_1": "יכין",
        "title_1": "יכין",
        "title_2": "דירה",
        "row_2": "דירה, שכונת הראשונים, רמת גן",
        "row_3": [
            "3 חדרים",
            "75 מ\"ר",
            "5"
        ],
        "row_4": [
            {
                "key": "rooms",
                "label": "חדרים",
                "value": 3
            },
            {
                "key": "floor",
                "label": "קומה",
                "value": 5
            },
            {
                "key": "SquareMeter",
                "label": "מ\"ר",
                "value": "75 "
            }
        ],
        "line_1": "3 חדרים",
        "line_2": "5",
        "external": [],
        "promotional_ad": 0,
        "ad_type": "ad",
        "type": "ad",
        "can_hide": 0,
        "is_hidden": 0,
        "img_url": null,
        "images": [],
        "images_urls": [
            "https://img.yad2.co.il/Pic/202112/26/2_5/o/y2_1_ukuxVegh6n_20211226.jpg",
            "https://img.yad2.co.il/Pic/202112/26/2_5/o/y2_2_3fp927WTwR_20211226.jpg",
            "https://img.yad2.co.il/Pic/202112/26/2_5/o/y2_3_m_Irw6M53g_20211226.jpg",
            "https://img.yad2.co.il/Pic/202112/26/2_5/o/y2_5__B1sJOfkG8_20211226.jpg"
        ],
        "images_count": 0,
        "merchant": true,
        "link_token": "rsyd3tb7",
        "ad_highlight_type": "yellow",
        "highlight_text": "בלעדי",
        "is_liked": 0,
        "like_count": 0,
        "line_1_text_color": "",
        "line_2_text_color": "808080",
        "can_change_layout": 1,
        "default_layout": "system",
        "remove_on_unlike": false,
        "video_url": null,
        "mp4_video_url": null,
        "updated_at": "עודכן היום",
        "price": "2,690,000 ₪",
        "currency": "₪",
        "uid": "N8D2X8rgP9614WMEXmmXP+nCmyIJp9robeBxtujUQW8=",
        "search_text": "דירה תיווך מכירה חדרים ב רמת גן , שכונת הראשונים , יכין $HomeNum קומה $Floor_text מתוך $TotalFloor_text קומות. $FurnitureInfo בפרויקט חדש בשכונת ראשונים, דירת 3 חד' חדשה ומרווחת, מלאה באור. פונה לחזית עם מרפסת שמש יפה. מעולה להשקעה/מגורים. קרובה לאזורי תעסוקה ומוסדות חינוך מעולים תחת תקופת אחריות ובדק מהקבלן! רם הנדלמן דירה 3 $Floor_text $TotalFloor_text $Amudim_text $Furniture_text $PandorDoors_text מיזוג מעלית $Parking_text $Grating_text גישה לנכים אזור רמת גן וגבעתיים $Immediate_text ממ\"ד מרפסת $storeroom_text $sunpatio_text ₪ $Meshupatz_text $Porch_text $yehidatdiur_text חדש (גרו בנכס) הצג רחוב $show_home_text $Tadiran_text עם מחיר, הצג רק מושבים וקיבוצים, מעלית, מיזוג, מיזוג, ממ\"ד, מרפסת, גישה לנכים, בבלעדיות, הצג רחוב 3 חדרים | 75 מ״ר | 5 יכין , שכונת הראשונים",
        "ad_number": 97586675,
        "customer_id": 6702036,
        "cat_id": "2",
        "subcat_id": "5",
        "record_id": 2588167,
        "date_added": "2021-12-26 15:11:42",
        "area_id": 3,
        "city": "רמת גן",
        "neighborhood": "שכונת הראשונים",
        "street": "יכין",
        "address_home_number": null,
        "date_of_entry": "2022-02-24 00:00:00",
        "contact_name": "רם הנדלמן",
        "date": "2022-04-23 17:21:25",
        "city_code": "8600",
        "id": "rsyd3tb7",
        "topAreaID_text": "מרכז",
        "AreaID_text": "אזור רמת גן וגבעתיים",
        "HomeTypeID_text": "דירה",
        "Parking_text": "",
        "Elevator_text": "מעלית",
        "AirConditioner_text": "מיזוג",
        "Grating_text": "",
        "mamad_text": "ממ\"ד",
        "patio_text": "מרפסת",
        "storeroom_text": "",
        "handicapped_text": "גישה לנכים",
        "Immediate_text": "",
        "PandorDoors_text": "",
        "Furniture_text": "",
        "Meshupatz_text": "",
        "sunpatio_text": "",
        "AssetClassificationID_text": "חדש (גרו בנכס)",
        "Rooms_text": 3,
        "Amudim_text": "",
        "yehidatdiur_text": "",
        "Tadiran_text": "",
        "show_street_text": "הצג רחוב",
        "show_home_text": "",
        "Porch_text": "",
        "currency_text": "₪",
        "square_meters": 75,
        "line_3": "Home Hero Start-Up",
        "merchant_name": "Home Hero Start-Up",
        "office_logo_url": "//img.yad2.co.il/Pic/TivMiniSite/y2_1_05909_20200915160932.jpeg?t=1650723712123",
        "IsVisibleForReco": false,
        "hood_id": 1647,
        "Rooms": 3,
        "HomeTypeID": 1
    },
    {
        "order_type_id": 1,
        "background_color": "f0f0f0",
        "coordinates": {
            "latitude": "32.0806729545454",
            "longitude": "34.8048565"
        },
        "row_1": "שפירא",
        "title_1": "שפירא",
        "title_2": "דירה",
        "row_2": "דירה, שכונת הראשונים, רמת גן",
        "row_3": [
            "4 חדרים",
            "90 מ\"ר",
            "2"
        ],
        "row_4": [
            {
                "key": "rooms",
                "label": "חדרים",
                "value": 4
            },
            {
                "key": "floor",
                "label": "קומה",
                "value": 2
            },
            {
                "key": "SquareMeter",
                "label": "מ\"ר",
                "value": "90 "
            }
        ],
        "line_1": "4 חדרים",
        "line_2": "2",
        "external": [],
        "promotional_ad": 0,
        "ad_type": "ad",
        "type": "ad",
        "can_hide": 0,
        "is_hidden": 0,
        "img_url": "https://img.yad2.co.il/Pic/201909/10/2_5/o/o2_5_1_737088_20190910140900.jpg",
        "images": {
            "Image1": {
                "src": "https://img.yad2.co.il/Pic/201909/10/2_5/o/o2_5_1_737088_20190910140900.jpg"
            },
            "Image2": {
                "src": "https://img.yad2.co.il/Pic/201909/10/2_5/o/o2_5_2_735837_20190910140903.jpg"
            },
            "Image3": {
                "src": "https://img.yad2.co.il/Pic/201909/10/2_5/o/o2_5_3_734802_20190910140903.jpg"
            },
            "Image4": {
                "src": "https://img.yad2.co.il/Pic/201909/10/2_5/o/o2_5_4_739748_20190910140903.jpg"
            },
            "Image5": {
                "src": "https://img.yad2.co.il/Pic/201909/10/2_5/o/o2_5_5_738466_20190910140902.jpg"
            }
        },
        "images_urls": [
            "https://img.yad2.co.il/Pic/201909/10/2_5/o/o2_5_1_737088_20190910140900.jpg",
            "https://img.yad2.co.il/Pic/201909/10/2_5/o/o2_5_2_735837_20190910140903.jpg",
            "https://img.yad2.co.il/Pic/201909/10/2_5/o/o2_5_3_734802_20190910140903.jpg",
            "https://img.yad2.co.il/Pic/201909/10/2_5/o/o2_5_4_739748_20190910140903.jpg",
            "https://img.yad2.co.il/Pic/201909/10/2_5/o/o2_5_5_738466_20190910140902.jpg"
        ],
        "images_count": 5,
        "merchant": true,
        "link_token": "svzmxi",
        "ad_highlight_type": "none",
        "highlight_text": "",
        "is_liked": 0,
        "like_count": 0,
        "line_1_text_color": "",
        "line_2_text_color": "808080",
        "can_change_layout": 1,
        "default_layout": "system",
        "remove_on_unlike": false,
        "video_url": null,
        "mp4_video_url": null,
        "updated_at": "עודכן היום",
        "price": "2,690,000 ₪",
        "currency": "₪",
        "uid": "RnnCEkApdmqi56uwnkGKSg==",
        "search_text": "דירה תיווך מכירה חדרים ב רמת גן , שכונת הראשונים , שפירא $HomeNum קומה $Floor_text מתוך $TotalFloor_text קומות. $FurnitureInfo על היציאה לתל אביב ובשכונה הכי מבוקשת ברמת גן..משופצת מהיסוד אדריכלית כחדשה  בסטנדרט הכי גבוה. Street נכסים דירה 4 $Floor_text $TotalFloor_text $Amudim_text $Furniture_text $PandorDoors_text מיזוג $Elevator_text $Parking_text $Grating_text גישה לנכים אזור רמת גן וגבעתיים מיידי $mamad_text מרפסת $storeroom_text $sunpatio_text ₪ $Meshupatz_text 1 $yehidatdiur_text משופץ הצג רחוב $show_home_text $Tadiran_text עם מחיר, עם תמונה, הצג רק מושבים וקיבוצים, מיזוג, מיזוג, מרפסת, גישה לנכים, מיידי, הצג רחוב 4 חדרים | 90 מ״ר | 2 שפירא , שכונת הראשונים",
        "ad_number": 72624867,
        "customer_id": 694395,
        "cat_id": "2",
        "subcat_id": "5",
        "record_id": 2203910,
        "date_added": "2018-06-24 21:49:33",
        "area_id": 3,
        "city": "רמת גן",
        "neighborhood": "שכונת הראשונים",
        "street": "שפירא",
        "address_home_number": null,
        "date_of_entry": "2022-01-19 00:00:00",
        "contact_name": "Street נכסים",
        "date": "2022-04-23 14:33:41",
        "city_code": "8600",
        "id": "svzmxi",
        "topAreaID_text": "מרכז",
        "AreaID_text": "אזור רמת גן וגבעתיים",
        "HomeTypeID_text": "דירה",
        "Parking_text": "",
        "Elevator_text": "",
        "AirConditioner_text": "מיזוג",
        "Grating_text": "",
        "mamad_text": "",
        "patio_text": "מרפסת",
        "storeroom_text": "",
        "handicapped_text": "גישה לנכים",
        "Immediate_text": "מיידי",
        "PandorDoors_text": "",
        "Furniture_text": "",
        "Meshupatz_text": "",
        "sunpatio_text": "",
        "AssetClassificationID_text": "משופץ",
        "Rooms_text": 4,
        "Amudim_text": "",
        "yehidatdiur_text": "",
        "Tadiran_text": "",
        "show_street_text": "הצג רחוב",
        "show_home_text": "",
        "Porch_text": "1",
        "currency_text": "₪",
        "square_meters": 90,
        "line_3": "נכסים street",
        "merchant_name": "נכסים street",
        "office_logo_url": "//img.yad2.co.il/Pic/TivMiniSite/logo100_2_7_749070_20190108200135-l.jpg?t=1650713638116",
        "office_about": "חברת נדל\"ן שמתמחה בשיווק ומכירת דירות יד 2 בערים ת\"א גבעתיים רמת גן וחולון.חברה ששמה דגש על השירות האישי והתאמת הדירה בדיוק לצרכי הלקוח.\r\nאם זה למגורים או להשקעה.",
        "IsVisibleForReco": false,
        "hood_id": 1647,
        "Rooms": 4,
        "HomeTypeID": 1
    },
    {
        "order_type_id": 1,
        "background_color": "f0f0f0",
        "coordinates": {
            "latitude": "32.0937641282051",
            "longitude": "34.7776329230769"
        },
        "row_1": "יחזקאל",
        "title_1": "יחזקאל",
        "title_2": "דירה",
        "row_2": "דירה, הצפון הישן - צפון, תל אביב יפו",
        "row_3": [
            "3 חדרים",
            "65 מ\"ר",
            "2"
        ],
        "row_4": [
            {
                "key": "rooms",
                "label": "חדרים",
                "value": 3
            },
            {
                "key": "floor",
                "label": "קומה",
                "value": 2
            },
            {
                "key": "SquareMeter",
                "label": "מ\"ר",
                "value": "65 "
            }
        ],
        "line_1": "3 חדרים",
        "line_2": "2",
        "external": [],
        "promotional_ad": 0,
        "ad_type": "ad",
        "type": "ad",
        "can_hide": 0,
        "is_hidden": 0,
        "img_url": "https://img.yad2.co.il/Pic/202002/02/2_5/o/o2_5_1_02216_20200202070243.jpg",
        "images": {
            "Image1": {
                "src": "https://img.yad2.co.il/Pic/202002/02/2_5/o/o2_5_1_02216_20200202070243.jpg"
            },
            "Image2": {
                "src": "https://img.yad2.co.il/Pic/202002/02/2_5/o/o2_5_2_01985_20200202070257.jpg"
            },
            "Image3": {
                "src": "https://img.yad2.co.il/Pic/202003/16/2_5/o/o2_5_3_02762_20200316130358.jpg"
            },
            "Image4": {
                "src": "https://img.yad2.co.il/Pic/202003/16/2_5/o/o2_5_4_05624_20200316130305.jpg"
            },
            "Image5": {
                "src": "https://img.yad2.co.il/Pic/202003/16/2_5/o/o2_5_5_05578_20200316130335.jpg"
            }
        },
        "images_urls": [
            "https://img.yad2.co.il/Pic/202002/02/2_5/o/o2_5_1_02216_20200202070243.jpg",
            "https://img.yad2.co.il/Pic/202002/02/2_5/o/o2_5_2_01985_20200202070257.jpg",
            "https://img.yad2.co.il/Pic/202003/16/2_5/o/o2_5_3_02762_20200316130358.jpg",
            "https://img.yad2.co.il/Pic/202003/16/2_5/o/o2_5_4_05624_20200316130305.jpg",
            "https://img.yad2.co.il/Pic/202003/16/2_5/o/o2_5_5_05578_20200316130335.jpg"
        ],
        "images_count": 5,
        "merchant": true,
        "link_token": "ty4c77",
        "ad_highlight_type": "none",
        "highlight_text": "",
        "is_liked": 0,
        "like_count": 0,
        "line_1_text_color": "",
        "line_2_text_color": "808080",
        "can_change_layout": 1,
        "default_layout": "system",
        "remove_on_unlike": false,
        "video_url": null,
        "mp4_video_url": null,
        "updated_at": "עודכן היום",
        "price": "2,750,000 ₪",
        "currency": "₪",
        "uid": "6JMqPIwI8YqZvifHXntwyQ==",
        "search_text": "דירה תיווך מכירה חדרים ב תל אביב יפו , הצפון הישן - צפון , יחזקאל $HomeNum קומה $Floor_text מתוך $TotalFloor_text קומות. $FurnitureInfo מציאה בצפון הישן והטוב!\r\n\r\nעורפית ושקטה! תקרות גבוהות, חדרים סופר מרווחים\r\n\r\nדירת 3 חד' אותנטית יפהפיה - ריצוף ירקרק עבודת יד\r\n\r\nשופצה לפני כ15 שנה, שמורה ובמחיר נהדר! מאיה אפרים דירה 3 $Floor_text $TotalFloor_text $Amudim_text ריהוט דלתות פנדור מיזוג $Elevator_text $Parking_text $Grating_text $handicapped_text אזור תל אביב יפו $Immediate_text $mamad_text מרפסת $storeroom_text $sunpatio_text ₪ $Meshupatz_text $Porch_text $yehidatdiur_text במצב שמור הצג רחוב $show_home_text מזגן תדיראן עם מחיר, עם תמונה, הצג רק מושבים וקיבוצים, מיזוג, מיזוג, מרפסת, דלתות פנדור, ריהוט, מזגן תדיראן, הצג רחוב 3 חדרים | 65 מ״ר | 2 יחזקאל , הצפון הישן - צפון",
        "ad_number": 45490065,
        "customer_id": 3188911,
        "cat_id": "2",
        "subcat_id": "5",
        "record_id": 2267365,
        "date_added": "2020-02-02 07:45:42",
        "area_id": 1,
        "city": "תל אביב יפו",
        "neighborhood": "הצפון הישן - צפון",
        "street": "יחזקאל",
        "address_home_number": null,
        "date_of_entry": null,
        "contact_name": "מאיה אפרים",
        "date": "2022-04-23 13:33:23",
        "city_code": "5000",
        "id": "ty4c77",
        "topAreaID_text": "מרכז",
        "AreaID_text": "אזור תל אביב יפו",
        "HomeTypeID_text": "דירה",
        "Parking_text": "",
        "Elevator_text": "",
        "AirConditioner_text": "מיזוג",
        "Grating_text": "",
        "mamad_text": "",
        "patio_text": "מרפסת",
        "storeroom_text": "",
        "handicapped_text": "",
        "Immediate_text": "",
        "PandorDoors_text": "דלתות פנדור",
        "Furniture_text": "ריהוט",
        "Meshupatz_text": "",
        "sunpatio_text": "",
        "AssetClassificationID_text": "במצב שמור",
        "Rooms_text": 3,
        "Amudim_text": "",
        "yehidatdiur_text": "",
        "Tadiran_text": "מזגן תדיראן",
        "show_street_text": "הצג רחוב",
        "show_home_text": "",
        "Porch_text": "",
        "currency_text": "₪",
        "square_meters": 65,
        "address_more": "הזמדנות נדירה!",
        "line_3": "אייל ארליך Tel Aviv Realty",
        "merchant_name": "אייל ארליך Tel Aviv Realty",
        "office_logo_url": "//img.yad2.co.il/Pic/TivMiniSite/f2e1ff6a-9ae1-42d7-abf0-217342cecbea.jpg?t=1650710039229",
        "office_about": "משרד שירות VIP אישי במכירה/קניה של נכסים בת\"א.\r\nהתמחות באזור מרכז ולב ת\"א, צפון ישן ושכונות דרומיות.",
        "IsVisibleForReco": false,
        "hood_id": 1483,
        "Rooms": 3,
        "HomeTypeID": 1
    },
    {
        "order_type_id": 3,
        "background_color": "fef0a9",
        "coordinates": {
            "latitude": "32.080739875",
            "longitude": "34.810271875"
        },
        "row_1": "ארלוזורוב",
        "title_1": "ארלוזורוב",
        "title_2": "דירה",
        "row_2": "דירה, רמת גן",
        "row_3": [
            "3 חדרים",
            "63 מ\"ר",
            "3"
        ],
        "row_4": [
            {
                "key": "rooms",
                "label": "חדרים",
                "value": 3
            },
            {
                "key": "floor",
                "label": "קומה",
                "value": 3
            },
            {
                "key": "SquareMeter",
                "label": "מ\"ר",
                "value": "63 "
            }
        ],
        "line_1": "3 חדרים",
        "line_2": "3",
        "external": [],
        "promotional_ad": 0,
        "ad_type": "ad",
        "type": "ad",
        "can_hide": 0,
        "is_hidden": 0,
        "img_url": null,
        "images": [],
        "images_urls": [
            "https://img.yad2.co.il/Pic/202204/13/2_5/o/y2_1_aysIvJck0o_20220413.jpeg",
            "https://img.yad2.co.il/Pic/202204/13/2_5/o/y2_2_fm8OQSju4__20220413.jpeg"
        ],
        "images_count": 0,
        "merchant": true,
        "link_token": "yatr1x5q",
        "ad_highlight_type": "yellow",
        "highlight_text": "בלעדי",
        "is_liked": 0,
        "like_count": 0,
        "line_1_text_color": "",
        "line_2_text_color": "808080",
        "can_change_layout": 1,
        "default_layout": "system",
        "remove_on_unlike": false,
        "video_url": null,
        "mp4_video_url": null,
        "updated_at": "עודכן היום",
        "price": "2,300,000 ₪",
        "currency": "₪",
        "uid": "wFrspiAQIdlUcvj5OdNZL85131cwBLW5qPx4g6vk7vA=",
        "search_text": "דירה תיווך מכירה חדרים ב רמת גן , $Neighborhood , ארלוזורוב $HomeNum קומה $Floor_text מתוך $TotalFloor_text קומות. $FurnitureInfo ברחוב ארלוזורוב רמת גן, בנין שנמצא בשלבים מתקדמים של תמ\"א (פינוי בינוי) מוצעת דירת 3 חדרים 63 מ\"ר משופצת ונעימה. מתאימה למגורים ולהשקעה. HOME MARKET דירה 3 $Floor_text $TotalFloor_text $Amudim_text $Furniture_text $PandorDoors_text מיזוג מעלית $Parking_text סורגים $handicapped_text אזור רמת גן וגבעתיים $Immediate_text $mamad_text $patio_text $storeroom_text $sunpatio_text ₪ משופצת $Porch_text $yehidatdiur_text משופץ הצג רחוב $show_home_text $Tadiran_text עם מחיר, הצג רק מושבים וקיבוצים, מעלית, מיזוג, מיזוג, סורגים, משופצת, בבלעדיות, הצג רחוב 3 חדרים | 63 מ״ר | 3 ארלוזורוב ,",
        "ad_number": 84406848,
        "customer_id": 6333804,
        "cat_id": "2",
        "subcat_id": "5",
        "record_id": 2645192,
        "date_added": "2022-04-13 13:15:48",
        "area_id": 3,
        "city": "רמת גן",
        "neighborhood": null,
        "street": "ארלוזורוב",
        "address_home_number": null,
        "date_of_entry": null,
        "contact_name": "HOME MARKET",
        "date": "2022-04-23 15:36:21",
        "city_code": "8600",
        "id": "yatr1x5q",
        "topAreaID_text": "מרכז",
        "AreaID_text": "אזור רמת גן וגבעתיים",
        "HomeTypeID_text": "דירה",
        "Parking_text": "",
        "Elevator_text": "מעלית",
        "AirConditioner_text": "מיזוג",
        "Grating_text": "סורגים",
        "mamad_text": "",
        "patio_text": "",
        "storeroom_text": "",
        "handicapped_text": "",
        "Immediate_text": "",
        "PandorDoors_text": "",
        "Furniture_text": "",
        "Meshupatz_text": "משופצת",
        "sunpatio_text": "",
        "AssetClassificationID_text": "משופץ",
        "Rooms_text": 3,
        "Amudim_text": "",
        "yehidatdiur_text": "",
        "Tadiran_text": "",
        "show_street_text": "הצג רחוב",
        "show_home_text": "",
        "Porch_text": "",
        "currency_text": "₪",
        "square_meters": 63,
        "line_3": "Home Market",
        "merchant_name": "Home Market",
        "office_logo_url": "//img.yad2.co.il/Pic/TivMiniSite/y2_1_04702_20200610130624.jpeg?t=1650717395289",
        "office_about": "אין כמו להיכנס לדירה חדשה ולדעת שמצאתם בית. אנחנו ב-Home marketמכירים את הרגע הזה מקרוב וכדי לאפשר לכל אחד ואחת מכם לחוות אותו, פיתחנו פלטפורמת חיפוש דירות חכמה שלומדת אתכם לעומק ומוצאת עבורכם את הנכס שמתאים לכם בדיוק. היכולות הטכנולוגיות שלנו מצטרפות לידע וניסיון של עשרות שנים בתחום,יחס אישי, ליווי מקצועי מסור וכל מה שצריך כדי להפוך את תהליך החיפוש שלכם להרבה יותר מדויק, פשוט ומהנה. כי אין דבר שיותר מרגש אותנו מלמצוא בשבילכם את הבית שחיפשתם, ולהגיד לכם ?תתחדשו!?",
        "IsVisibleForReco": false,
        "hood_id": 1477,
        "Rooms": 3,
        "HomeTypeID": 1
    }
]

module.exports = {housingPrices}